### ISSUE TITLE
Organization Name Mispelling

### ISSUE THREAD

**Issue by mstraughan86** [ARKeth/platform#1]
@Josefsosa Unfortunately, the organization name has a misspelling!

ARKeth Platfrom
ARKeth Platform

The "r" and the "o" are swapped. Whoops! Otherwise, interesting endeavor from the whitepaper.

**Comment by mstraughan86** [comment]
Resolved.

**Comment by Josefsosa** [comment]
Hi  Michael, thanks for catching that, I have fixed the typo.

Are you interested in learning more and participating in ARKeth open source
projects. I have a elevator deck here. Also looking for advisory roles send
me your BIO and image and I will add you in the role you would like.

Thanks,

Jose F. Sosa
ARKeth CEO

**Comment by mstraughan86** [comment]
I am slowly reading through the whitepaper to get a feel for the roadmap/timeline of the project. Yes, I am interested and would like to be included in the project development, although I have no etherium development knowledge. You can find a link to my CV right [here](https://www.linkedin.com/in/mstraughan).
